src/app/home/components/Navlist.tsx

- Jira Link: [TYPESCRIPT - Menú Comunidad Funcional](https://scrumlatamc.atlassian.net/browse/PWS1-6?atlOrigin=eyJpIjoiYzM1YzNiMzJlZjJiNDRiMmE5NjkyNTA1N2VhNTc1M2YiLCJwIjoiaiJ9)
Se corrijio error al dar click a los desplegables de comunidad.
Detalles:
- Cambio de la funcion onclick en la lista de comunidad.
- Vista A: Home, comunidad y onboarding
- Test A1: Ejecutando accion click en los componentes onboarding y los squads
1. Navegar sobre el componente Navbar
2. Desplegar el submenu comunidad
3. Ejecturar accion click sobre las opciones los squads y onboarding

fix: links comunity

---

src/app/home/components/Navbar.tsx

- Jira: https://scrumlatamc.atlassian.net/browse/PWS1-67
Corrección de que la imagen se achique de más en algunas dimensiones responsive
Detalles:
- Se modificaron algunas propiedades de tailwind para evitar que la imagen se vuelva demasiado pequeña
- Vista A: Mobile
- Test A1: Iphone XR
- Test A2: Iphone SE
- Test A3: Samsung Galaxy s8+
- Test A4: Samsung Galaxy s20 Ultra
1. Estando en el inicio, cambiar las dimensiones de la página a mobile.
Error en los componentes <FlagsCommunity /> y <Sponsors />, hay que ocultarlos para que se puedan ver los cambios de manera correcta

Pws1 67/fix navbar

---

src/app/home/components/Reviews.tsx
src/data/data.ts

- Jira: https://scrumlatamc.atlassian.net/jira/software/projects/PWS1/boards/2?selectedIssue=PWS1-76
Arreglo de la sección reviews en la vista principal
Detalles:
- Se estiló el tamaño de las reviews
- Se modificó la lógica de su funcionamiento para solo expandir el comentario seleccionado
- Se solucionó el problema de que al moverse por el carrusel el comentario seguia extendido
- Vista A: Web
- Test A1: OperaGX Pantalla de 1920 x 1080
- Test A2: Chrome Pantalla de 1920 x 1080
- Vista B: Mobile
- Test B1: Iphone XR
- Test B2: Iphone SE
1. Navegar en el home hacia abajo hasta encontrar la sección de "Que opina nuestra comunidad"

Pws1 76/reviews fix

---

src/app/home/components/Navlist.tsx
src/data/data.ts

- Jira: No posee
Arreglo de errores para el deploy
Detalles:
- Se cambiaron links en Navlist
- Se cambiaron links de fotos a firebase
Vista A: Web
Test A1: OperaGX Pantalla de 1920 x 1080
Test A2: Chrome Pantalla de 1920 x 1080
Vista B: Mobile
Test B1: Iphone XR
Test B2: Iphone SE
1. Navegar a home, clickear en la navbar en la parte de novedades.
2. Hacer click en cualquierda de las 3 secciones

fix: fixed some deploy errors!

---

src/app/home/components/Navbar.tsx

- Jira/Trello/Toro Link: Nombre del ticket o feature
Breve descripción: Implementación de la funcionalidad para [describir la tarea realizada]. Se añadió la vista para [nombre de la vista], se integraron las APIs necesarias y se realizaron las validaciones correspondientes en el frontend.
Detalles:
- Se añadió un nuevo componente NombreDelComponente para [descripción de lo que hace el componente].
- Se actualizaron los estilos utilizando [framework o librería de estilos] para mejorar la UI/UX.
- Integración con el backend para [descripción de la integración].
- Validaciones añadidas para [explicar cualquier validación nueva].
- Refactorización de [cualquier código relevante] para [motivo del refactor].
Se realizaron pruebas en las siguientes vistas para asegurar que los cambios funcionen …

fix: change route register

---

next.config.mjs
package-lock.json
src/app/home/components/Navbar.tsx
src/app/home/components/Navlist.tsx

- Jira: https://scrumlatamc.atlassian.net/browse/PWS1-60
Se arreglaron problemas en la navbar, tanto sus funcionalidades como en estilos
Detalles:
- Ahora queda resaltado en la navbar la posicion en la página donde se está.
- Se arregló algunos href que enviaban a links erroneos
- Se agregaron estilos a la navbar para que quede como el figma
Vista A: Mobile
-Test A1: OperaGx Pantalla Iphone XR
Vista B: Desktop
-Test B1: OperaGx de 1920 x 1080
-Test B1: OperaGx 1440 x 1080
1. En el home, hacer click a cualquier boton de la Navbar

fix: navbar styles and fonts

---

src/app/home/components/Navbar.tsx

PR test to check if the img works

fix: image 

---

src/app/home/components/CounterToCommunity.tsx
src/app/home/components/FlagsCommunity.tsx
src/app/home/components/News.tsx
src/app/home/components/WelcomeToCommunity.tsx

- Jira: https://scrumlatamc.atlassian.net/jira/software/projects/PWS1/boards/2?selectedIssue=PWS1-218
Se solucionaron errores de estilos en el home
Detalles:
- Se agregó un espacio desde la Navbar hasta el "Bienvenidos"
- Se agregaron estilos al botón de "Únete a nosotros"
- Se agregó mas espacio entre bandera y bandera 
Vista A: Mobile
-Test A1: OperaGx Pantalla Iphone XR
Vista B: Desktop
-Test B1: OperaGx de 1920 x 1080
-Test B1: OperaGx 1440 x 1080
1. Dirigirse al home de la página

fix: styles in home page

---

src/app/home/components/Navlist.tsx

- Jira Link: [PWS1-69 Desplegables y Submenús](https://scrumlatamc.atlassian.net/browse/PWS1-69?atlOrigin=eyJpIjoiZjk1NDVhYWJhYzU0NDEzMWIwY2Y3ODJkYjNlZjczZDUiLCJwIjoiaiJ9)
Se dio correccion a los desplegables de Navbar, mejorando la experiencia de usuario
Detalles:
- Se removio la funcionalidad de paso por encima del desplegable
- Se añadio la funcionalidad de dar click en una parte externa del dropdown para cerrar
- Vista A: Activacion de deplegables
- Test A1: Verifica que los desplegables de la navbar no se cierran al quitar el cursor del espacio ocupado por el componente
- Test A2: Asegura que se mantengan abiertos y se cierren solo al dar click en cualquier otra seccion de pantalla …

fix: fixed clicks dropdown navbar

---

src/app/super-admin-dashboard/allies/components/DesktopSidebar.tsx
src/app/super-admin-dashboard/allies/components/PieChart.tsx
src/app/super-admin-dashboard/dashboard/page.tsx

- Jira/Trello/Toro Link: PWS1-227-SuperAdmin
Breve descripción: Implementación de la funcionalidad para Pie Chart y cuadros estadìsticos de super admin.
Detalles:
- Se actualizaron los estilos utilizando Pie Chart para mejorar la UI/UX.
- Integración con el backend para realizar consultas con datos reales de la página.
- Vista A: Dashboard
- Test A1: Verifica que la página Dashboard se SuperAdmin traiga los datos de la DB
1. Navegar a la vista Dashboard de SuperAdmin.
2. Verificar que los datos y el gráfica cargan adecuadamente.

feat: add pie chart

---

src/app/globals.css
src/app/sponsors/components/imageUpload.tsx
src/app/sponsors/layout.tsx
src/app/sponsors/offerts/page.tsx
src/app/sponsors/profile/sponsorProfile.tsx
src/app/super-admin-dashboard/allies/components/sponsorsList.tsx
src/app/super-admin-dashboard/allies/page.tsx
src/app/super-admin-dashboard/events/page.tsx
src/app/super-admin-dashboard/members/components/membersList.tsx
src/app/super-admin-dashboard/members/page.tsx
src/app/super-admin-dashboard/memberships/page.tsx

- Jira: no tiene
Breve descripción: Se arregló el formulario de Ofertas para que cumpla con los datos del Figma, se agregó el listado de sponsors en el dashboard de superadmin y también se crearon vistas para completar las paginas del dashboard de superadmin.
Detalles:
-Nuevo formulario de Ofertas
-Vista de "Sponsors" ahora muestra el listado de sponsors
-Vista de "Miembros" en superadmin-dashboard hecha
-Vista de "Eventos" en superadmin-dashboard hecha
-Vista de "Membresias" en superadmin-dashboard hecha
- Vista A: Web 
- Test A1: OperaGX 1920x1080 
- Test A2: OperaGX 1440x1080
- Vista Mobile: no posee
A: Dashboard de superadmin
1. Desde el home, ir a "iniciar sesión" e ingresar con una …

Offerts fix // Superadmin Dashboard Fill

---

src/app/home/components/Sponsors.tsx
src/data/data.ts

- Jira: No tiene
Breve descripción: Se agregaron los nuevos sponsors y eliminaron los que ya no formaban parte de la comunidad del carrusel del home
Detalles:
- Se modificó el archivo "data" para agregar/eliminar los sponsors
- Vista A: 
OperaGX -> 1920x1080px
1. Desde el home, scrollear hacia abajo hasta ver el carrusel con los sponsors

feat: deleted and added sponsors in home

---

src/app/community/components/profileCardSection.tsx
src/app/community/components/profileSection.tsx
src/app/community/interfaces/profileCardInterface.tsx
src/app/community/squads/page.tsx
src/data/data.ts

Se añadio la informacion de todos los miembros de los equipos de los squads junto a su descripcion, bandera y link a linkedin, y añadiendo una mejora, haciendo ciclico el swiper y aumentando el tiempo de espera que muestra cada seccion
Detalles:
- Se pasaron los datos de los miembros de los squads al archivo data, para mejorar la calidad de codigo
- Se actualizaron las fotos de los perfiles 
- Se cambio la descripcion y los titulos de los equipos
- Se añadio la propiedad loop al swiper, para que pueda rotar todo el segmento de equipo
- Se añadieron las banderas de cada miembro de equipo

Refactor team members data

---

src/app/users/components/countries-dropdown.tsx
src/app/users/components/editUserProfile.tsx
src/app/users/components/imageUpload.tsx
src/app/users/components/profileImageUploadModal.tsx
src/app/users/profile/userProfile.tsx
src/interfaces/index.ts

Implementación de la funcionalidad completa para la visualización y gestión del perfil de usuario. Se añadió la vista para el perfil del usuario (`UserProfile.tsx`), un formulario de edición de datos (`EditUserProfile.tsx`), y un modal con un componente dedicado (`ProfileImageUploadModal.tsx` y `ImageUpload.tsx`) para el cambio de la foto de perfil utilizando Cloudinary (a través del backend). Se integraron las APIs necesarias y se consideraron las validaciones correspondientes en el frontend.
Detalles:
- Se añadió un nuevo componente `UserProfile.tsx` para mostrar la información del perfil del usuario, incluyendo nombre, email, país (mostrando el primero de la lista y su bandera), membresía, fecha de ingreso y foto de perfil con un fallback predeterminado.
- Se añadió un nuevo componente …

Feature: Desarrollo completo del perfil de usuario con edición de datos y cambio de foto de perfil

---

src/app/activities/components/eventFeature.tsx
src/app/activities/components/heroSection.tsx
src/app/activities/components/workshopFeature.tsx
src/app/activities/page.tsx
src/app/community/products&services/page.tsx
src/app/home/components/CounterToCommunity.tsx
src/app/home/components/DiscoverCommunity.tsx
src/app/home/components/FlagsCommunity.tsx
src/app/home/components/JoinOurCommunity.tsx
src/app/home/components/Navbar.tsx
src/app/home/components/Navlist.tsx
src/app/home/components/News.tsx
src/app/home/components/Reviews.tsx
src/app/home/components/Sponsors.tsx
src/app/home/components/WelcomeToCommunity.tsx
src/app/layout.tsx
src/app/page.tsx

- Jira Link: 
1. https://scrumlatamc.atlassian.net/browse/PWS1-316
2. https://scrumlatamc.atlassian.net/browse/PWS1-342
3. https://scrumlatamc.atlassian.net/browse/PWS1-328
Se corrigieron problemas en las vistas que generaban molestias, slides y otros inconvenientes en la vista web de la página
Detalles:
- Se eliminó el botón de suscribirse en la esquina superior derecha de la página
- Se corrigieron errores de dimensiones lo que hacia que se generen slides horizontales en muchas vistas
- Se le agregó un w-max a la planilla con las tarjetas de los sponsors
- Se modificó en la Navbar que "Actividades" ya no deja un dropdown, sino que directamente redirije a la seccion "Actividades"
1. Navegar a la vista Home.
2. Ir a la Navbar y hacer click en "Actividades".
3. Ir a "Comunidad" e ir a la …

fix: horizontal slide on all views

---

src/app/home/components/JoinOurCommunity.tsx
src/app/home/components/WelcomeToCommunity.tsx
src/core/PrimaryButton.tsx
src/data/images_url.ts

- Jira/Trello/Toro Link: [DEV Actualizar colores e imágenes de sección bienvenida en el HOME](https://scrumlatamc.atlassian.net/browse/PWS1-343?atlOrigin=eyJpIjoiMDFjNmU0NzFiNDk0NGRlMTkyOGExYzczOWE2NjE0YzIiLCJwIjoiaiJ9)
Rediseño nuevo estilo seccion **bienvenido a la comunidad** 
Detalles:
- Se rediseño el formato de los textos y se agrego un nuevo parrafo basado en el diseño
- Se actualizo la imagen usada
- Se implementaron los nuevos colores

style: add new style welcome to comunity

---

src/app/home/components/ActivitiesHome.tsx
src/app/home/components/ActivitiesSlider.tsx
src/app/home/components/CommunityActivities.tsx
src/app/home/components/CounterToCommunity.tsx
src/app/home/components/MainActivity.tsx
src/app/home/components/Sponsors.tsx
src/app/home/components/WelcomeToCommunity.tsx

- Jira: No tiene
Breve descripción: Arreglos varios en la página para solucionar errores de dimensiones
Detalles:
- Se modificó el texto de un componente del home para que esté centrado
- Se modificó el componente con el listado de actividades del home para que se vea en mobile
- Se achicaron los logos de los sponsors en la animacion que salia en el home 
- El primer componente del home tuvo sus margenes solucionados y el boton de unirse a nosotros ya funciona
1. En el home de la página, scrollear hacia abajo.

Overall fixes

---

src/app/activities/page.tsx
src/app/editor/components/ActivityList.tsx
src/app/editor/components/createActivity.tsx
src/app/editor/components/editActivity.tsx
src/app/editor/components/editorSidebar.tsx
src/app/editor/components/imgs/imageUpload.tsx
src/app/editor/components/successModal.tsx
src/app/editor/layout.tsx
src/app/editor/page.tsx
src/app/home/components/Navbar.tsx
src/assets/UploadIcon.tsx

- Jira/Trello/Toro Link: [DEV Implementar dashboard del rol Editor para gestión de actividades en el portal Scrum Latam](https://scrumlatamc.atlassian.net/browse/PWS1-387?atlOrigin=eyJpIjoiNmUzYjcwYTc2M2NlNDEwYWJlZDZhMjdhZTIyNTg0N2UiLCJwIjoiaiJ9)
Creacion del perfil del editor manteniendo el diseño en figma
Detalles:
- Se añadio la nueva seccion del editor
- Se añadieron componentes como lista de actividades, formulario de edicion y vista de actividades,
- Se añadieron los filtros para la lista de actividades
- Boton nueva actividad, funcional
- En el formulario de edicion se añadio el boton de borrar actividad
- Vista A: Perfil de usuario con rol editor
- Test A1: Verifica que la lista …

feat: new profile editor

---

src/app/community/products&services/components/sponsorCard.tsx
src/app/community/products&services/page.tsx
src/app/history/page.tsx
src/app/home/components/ActivitiesHome.tsx
src/app/home/components/Footer.tsx
src/app/home/components/JoinOurCommunity.tsx
src/app/home/components/Reviews.tsx
src/app/home/components/Sponsors.tsx
src/app/onboarding/travel/page.tsx
src/data/data.ts

- Jira: https://scrumlatamc.atlassian.net/browse/PWS1-373
https://scrumlatamc.atlassian.net/browse/PWS1-367
Breve descripción: Se arreglaron pequeños errores de diseño del portal, desde las reviews en la parte inferior del home, hasta en el onboarding, llegando hasta la parte de "Nuestros inicios".
Detalles:
- Se modificaron los componentes del onboarding para que tengan relacion con el figma
- Se cambiaron las fotos de perifl de las reviews
- Se le agregaron a las reviews el texto indicado (aunque recortado) en los comentarios
- Se agregó un padding en la version mobile de "Mis inicios"
- Vista A: Web
- Test A1: OperaGX 1920x1080
- Test A2: OperaGX 1440x1080
- Vista B: Mobile
- Test B1: …

fix: overall changes

---

src/app/activities/components/WeeklyActivityHero.tsx
src/app/activities/components/activityCards.tsx
src/app/activities/components/activityTypeCard.tsx
src/app/components/RouteProtection.tsx
src/app/context/AuthContext.tsx
src/app/context/RegisterContext.tsx
src/app/editor/layout.tsx
src/app/history/page.tsx
src/app/home/components/ActivitiesSlider.tsx
src/app/home/components/Footer.tsx
src/app/home/components/MainActivity.tsx
src/app/home/components/Navlist.tsx
src/app/home/components/UserDropdown.tsx
src/app/hooks/useRouteProtection.tsx
src/app/onboarding/travel/page.tsx
src/app/sponsors/layout.tsx
src/app/super-admin-dashboard/layout.tsx
src/app/users/components/ActivityCard.tsx
src/app/users/profile/userProfile.tsx
src/data/data.ts

Breve descripción: Arreglos generales de la página
Detalles:
-Las descripciones de las actividades del home ya no aparecen en version mobile
-Terminos y condiciones ahora si abre el modal
-Espacio entre banners de la sección "/activities" ahora tiene el espaciado correcto
-"/history" ahora tiene el titulo con un margen correcto en version mobile
-Alineado el texto de la Navlist
-Ahora se toma el nombre del usuario al iniciar sesión (o companyName si es un sponsor)
-Rutas protegidas por roles
-<ActivityCard" de "Mis actividades" ahora tiene altura correspondiente
-"Cambiar foto de perfil" en el dashboard de usuario ya no aparece cuando se está en modo edición
-Onboarding rediseñado
- Vista …

Overall fixes 2

---

src/app/community/products&services/components/sponsorCard.tsx
src/app/editor/components/ActivityList.tsx
src/app/editor/page.tsx
src/app/users/activities/page.tsx

- Jira/Trello/Toro Link: [PWS1-419 En sponsor, que Andes lleve a su pagina web en vez de su perfil](https://scrumlatamc.atlassian.net/browse/PWS1-419)
- [PWS1-422 Llega mal el horario al calendar (fijarse si es por el formateo de horas)](https://scrumlatamc.atlassian.net/browse/PWS1-422)
- [PWS1-423 Formatear hora en el perfil "Mis Actividades"](https://scrumlatamc.atlassian.net/browse/PWS1-423)

Pws1 395 activity list

---

src/app/sponsors/components/editSponsorProfile.tsx

- Jira/Trello/Toro Link: Nombre del ticket o feature
Correccion error cuando el sponsor no tiene certificados, ahora puede añadir desde cero certificados

fix: add certificate sponsor

---

src/app/activities/components/WeeklyActivityHero.tsx
src/app/activities/components/activityTypeCard.tsx
src/app/community/offerts/[id]/page.tsx
src/app/community/offerts/components/offertsCard.tsx
src/app/editor/components/createActivity.tsx
src/app/home/components/Footer.tsx
src/app/home/components/JoinOurCommunity.tsx
src/app/home/components/Navbar.tsx
src/app/home/components/NavlistMobile.tsx
src/app/home/components/UserDropdown.tsx
src/app/sponsors/profile/sponsorProfile.tsx
src/hooks/useDisplayName.ts

Breve descripción: Resolucion de problemas a nivel general de la página
Detalles:
-En la Navbar mobile, que aparezca el "Hola Usuario" aparte de la foto de perfil - Fixed
-En Sponsors ("community/offerts/[id]") esta mál la foto de logo (muy grande en mobile) y la card en mobile tiene mal los textos (el tamaño) -Fixed
-En mobile, falta el logo en el footer - Fixed
-Ver parte inferior de la tarjeta /community/offerts/[id], checkear el padding bottom de ese componente - Fixed
-Ver las tarjetas de filtros de actividades de la seccion de actividades, tienen espaciado a su derecha en version mobile - Fixed
-Los horarios cargados de las actividades cuando se crea una en el perfil del editor estan mal- Fixed
FALTA DETALLES EN NAVBAR - No llegaron para la entrega hoy

feat: avances entrega final

---

src/app/editor/components/editActivity.tsx
src/app/editor/page.tsx
src/app/sponsors/components/editSponsorProfile.tsx
src/app/sponsors/mis-publish/page.tsx
src/app/sponsors/profile/sponsorProfile.tsx
src/app/super-admin-dashboard/activities/components/ActivityList.tsx
src/app/super-admin-dashboard/activities/page.tsx
src/app/super-admin-dashboard/allies/page.tsx
src/app/users/components/ActivityCard.tsx

Correccion de seccion offers list para sponsor

Fix errors style

---

src/app/community/offerts/[id]/page.tsx
src/app/sponsors/mis-publish/page.tsx

Correccion de errores en certificados y ofertas de cada sponsor en el dashboard de cada sponsor

fix: fix certificates sponsors and offers profile sponsor

---

src/app/editor/components/editActivity.tsx

Actualizacion form de edicion de actividades del editor, ahora tendremos los mensajes de observaciones en color rojo

style: edit activity rol editor

---

src/app/activities/components/activityCards.tsx
src/app/home/components/WelcomeToCommunity.tsx
src/data/data.ts

- Jira: No tiene
Breve descripción: Cambio de fotos en el home y activities
Detalles:
- Se cambió la foto de bienvenida en el home por la indicada por Ruben
- Se cambiaron las fotos de la sección de actividades por las indicadas por Ruben
1. Entrar a la pagina y ver el home
2. Ir a /activities y mirar las tarjetas de filtros

feat: new pictures

---

src/app/editor/components/editActivity.tsx
src/app/login/components/LoginForm.tsx

Style update activity
